version: '2'
services:
  postgres:
    container_name: api_controle_veiculos
    image: postgres:11.5
    restart: always
    environment:
      - POSTGRES_USER=scv
      - POSTGRES_PASSWORD=scv
      - POSTGRES_DB=scv
    ports:
      - 5432:5432
